### ISSUE TITLE
Rootfs header structure

### ISSUE THREAD

**Issue by asharpaev** [LeeXiaolan/hwfw-tool#1]
Do you know how to generate rootfs file.
I know some parts of header but not all.

**Comment by LeeXiaolan** [comment]
> Do you know how to generate rootfs file.

It seems just the standard squashfs.

**Comment by asharpaev** [comment]
my rootfs from HG8245H has 148 bites header and standard squashfs.
header contains:
- size of squashfs written in reverse
- date and time
- size of squashfs
- crc32 of squashfs 

and other datas which I don`t know it means.
